# ????? (MySQL 8.0+ ???? com.mysql.cj.jdbc.Driver)
jdbc.driver=com.mysql.cj.jdbc.Driver
# ????? URL
# pet_db ??????????
# serverTimezone=UTC ? Asia/Shanghai ?? 8.0 ???????
# useSSL=false ?????????? SSL ??
jdbc.url=jdbc:mysql://localhost:3306/pet_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
jdbc.username=dev_user
# ?????
jdbc.password=password123

//ceshitijiao123